version: "3.9"
services:
  postgres:
    image: postgres:15
    env_file: .env
    restart: unless-stopped
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"

  django:
    build: .
    image: django-docker
    env_file: .env
    expose:
      - "8000"
    environment:
      - "DJANGO_DEBUG=true"
    restart: always
    command: ["/docker-cmd.sh", "--debug"]
    volumes:
      - "./website/website/media:/usr/share/nginx/html/media"
      - "./website:/usr/src/website"  # mount the source code for watching changes
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.development.entrypoints=web"
      - "traefik.http.routers.django.rule=Host(`django.localhost`)"

  reverse-proxy:
    image: traefik:v2.9
    env_file: .env
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le-resolver.acme.httpchallenge=true"
      - "--certificatesresolvers.le-resolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le-resolver.acme.email=admin@yourdomain.com"
      - "--certificatesresolvers.le-resolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nginx:
    image: nginx:1.23-alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./website/website/media:/usr/share/nginx/html/media"
      - "./website/website/media:/usr/share/nginx/html/static"
    depends_on:
      - django
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.staticfiles.rule=PathPrefix(`/static/`) || PathPrefix(`/media/`)"
      - "traefik.http.routers.staticfiles.entrypoints=web"
      - "traefik.http.routers.staticfiles.priority=2"
volumes:
  postgres-data:
  media-data:
  staticfiles-data:
